default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=1jHZbsNei5qA9kPkkJbxtgKL
    - vercel build --token=1jHZbsNei5qA9kPkkJbxtgKL
    - vercel deploy --prebuilt  --token=1jHZbsNei5qA9kPkkJbxtgKL
